version: '2'
services:
  requester:
    build:
      context: ./requester
    ports:
      - "3333:80"
    volumes:
      - ./requester:/var/www
      - ./utils:/var/utils
    links:
      - db:db
    depends_on:
      - db
  worker:
    build:
      context: ./worker
    volumes:
      - ./worker:/var/www
      - ./utils:/var/utils
    ports:
      - "2222:80"
    links:
      - db:db
  db:
    image: bitnami/mongodb:latest
    volumes:
      - ./data:/bitnami/mongodb
    ports:
      - "4444:27017"
