version: '2'
services:
  requester:
    build:
      context: ./src
    ports:
      - "3333:80"
    volumes:
      - ./src:/var/www
    command: "npm run dev-requester"
    links:
      - db:db
    depends_on:
      - db
  worker:
    build:
      context: ./src
    volumes:
      - ./src:/var/www
    ports:
      - "2222:80"
    command: "npm run dev-worker"
    links:
      - db:db
  db:
    image: mongo:latest
    volumes:
      - ./data2:/data/db
    ports:
      - "4444:27017"
  db-client:
    image: mongo-express:latest
    links:
      - db:mongo
    restart: always
    ports:
      - "5555:8081"
